name: "codon CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: pipinstallnumpy
          run: |
            python -m pip install --upgrade pip
            pip install numpy

        - name: Install Codon
          run: |
            /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
            echo "$HOME/.codon/bin" >> $GITHUB_PATH
      
        - name: Verify Codon installation
          run: codon --version
    
        - name: Run Codon script
          run: codon run -release hello.py